// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dirzpszurrqdeopfnyku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpcnpwc3p1cnJxZGVvcGZueWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjEyNDQsImV4cCI6MjA3MTQzNzI0NH0.26MUvaGEX6txG-DpQ_TN9o_akqfpJ30IvvxDBTjvCMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});